[project]
name = "compare-between-threadpool-and-processpool"
version = "0.1.0"
description = "benchmark between threadpool and processpool"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "matplotlib>=3.10.8",
    "numpy>=2.4.2",
    "py-cpuinfo>=9.0.0",
    "rich>=14.3.3",
]
